version: '3.8'

services:
  app:
    image: php:7.4-apache
    container_name: php_app
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=newsportal

  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newsportal
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql


volumes:
  db_data:
